Use github.com/cention-nazri/translator instead of github.com/st3v/translator
Upstream hasn't merged language detection pull request yet.

Changes done by:

  $ gofmt -w -r '"github.com/st3v/translator" -> "github.com/cention-nazri/translator"' .

Without this fix compilation of cention-babeld fails:

  ./main.go:456: cannot use microsoft.NewTranslator(c.Microsoft.Id, c.Microsoft.Secret) (type "github.com/st3v/translator"
  .Translator) as type "github.com/cention-nazri/translator".Translator in assignment:
          "github.com/st3v/translator".Translator does not implement "github.com/cention-nazri/translator".Translator (wro
  ng type for Languages method)
                  have Languages() ([]"github.com/st3v/translator".Language, error)
                  want Languages() ([]"github.com/cention-nazri/translator".Language, error)